### ISSUE TITLE
Does not run on Windows

### ISSUE THREAD

**Issue by ilog2000** [patbenatar/vscode-advanced-new-file#1]
I gave it a try but it does not run on my Windows machine. After installation and VSCode re-load I always see a warning message box:

> Running the contributed command:'extension.advancedNewFile' failed.

on pressing Ctrl+Alt+N. If I call it via Ctrl+Shift+P, then I see an error box with the same message.

Windows 10 64-bit. VSCode 1.8.

**Comment by tolgabalci** [comment]
I have the same exact issue.
Windows 10 64-bit. VSCode 1.8.1

**Comment by smukkekim** [comment]
This used to work just fine on my windows machine.
I'm assuming there is some clash with updated vs code...

**Comment by patbenatar** [comment]
Confirmed, doesn't work on Windows. Debugging a bit and traced it to glob-fs which doesn't support Windows (see https://github.com/jonschlinkert/glob-fs/issues/10). Will work on switching to node-glob.

**Comment by patbenatar** [comment]
@smukkekim @tolgabalci @ilog2000 please try out version 0.1.2 just published to VS marketplace and let me know if you continue to have issues on Windows.

**Comment by smukkekim** [comment]
There is no longer an error - but nothing happens at all now. Both via ctrl+alt+n and via ctrl+shift+p and selecting the command.

**Comment by patbenatar** [comment]
@smukkekim what version of VS Code?

**Comment by patbenatar** [comment]
@smukkekim also, if you wouldn't mind helping me debug:

1. Clone this repo (https://github.com/patbenatar/vscode-advanced-new-file.git)
2. npm install
3. "Launch Extension" in the left-side debug panel of VS Code
4. Try to activate it in the new VS Code window that opens
5. In the parent VS Code window, do you see any errors in the "Output" or "Debug Console" bottom panels?

**Comment by smukkekim** [comment]
I have just tested it again on my home computer (previous report was after testing on my pc at work).
It works just fine now!
I will have to figure out, what is different between the home- and work-installations.
Sorry!

**Comment by patbenatar** [comment]
@smukkekim good news! Definitely let me know if you're able to debug the work setup as there may be others affected by the issue you've ran into there

**Comment by tolgabalci** [comment]
@patbenatar Thank You!  It now works!
I am using: VSCode 1.8.1 + Windows 7 Enterprise SP1

**Comment by smukkekim** [comment]
Ok... It turns out, it actually works, but is VERY slow in large projects...
If I have a few folders in the project, the extension opens near-instantly

...but my current main project at work, has 3,000+ folders. It takes approx. 30 seconds for the extension dialog to open, after pressing the shortcut.

I assume it's because it is building the dialog for selecting start-path. 
(Why does it not just use the current project root folder as start-path automatically?)

**Comment by patbenatar** [comment]
@smukkekim opened a dedicated issue for that here: #4
