### ISSUE TITLE
Can't create a new file when file is open

### ISSUE THREAD

**Issue by aindriu80** [patbenatar/vscode-advanced-new-file#109]
Advanced New File has been working great for me for a long time but recently I can no longer create a new file when I have another file open.  I have started doing some PHP code and installed some extensions for that so I am wondering is that related.  The extension does work however if I click out of a file I'm working on - like clicking on the files in Explorer

With so many keyboard shortcuts, I have CTRL ALT and N mapped to create a new file.  
![2022-06-09_11-54](https://user-images.githubusercontent.com/8885837/172831110-d2dda77d-dc49-4fb8-9f02-11f1143c1664.png)

I made a video ->

https://youtu.be/9HIArdbyxV8

I start out in the file and the shortcut doesn't work, then I select a folder on the right hand side and the shortcut works.

What could be causing the extension not to trigger? It does work but its annoying have to exit the file I'm working on.

**Comment by patbenatar** [comment]
@aindriu80 this looks to me like a keyboard shortcut conflict -- ie while you have an editor focused, some other plugin or VS Code itself is intercepting the keyboard shortcut. Are you able to launch the extension from the command palette: Ctrl+Shift+P and then select "Advanced New File" ?

**Comment by aindriu80** [comment]
Yes, it was a shortcut conflict, I was sure I checked but it's back working again, great extension!

**Comment by patbenatar** [comment]
Glad to hear it!
