### ISSUE TITLE
Brace expansion feature not working

### ISSUE THREAD

**Issue by sugamkarki** [patbenatar/vscode-advanced-new-file#111]
```index.{html,css}``` should create two files ```index.html``` and ```index.css```. But I am getting a single file ```index.{html,css}```

**Comment by Ahmed-ata112** [comment]
Yes, it doesn't work, and I think it's because of an update in the braces package.
I tried to solve it but still not really tested  yet and you can check it [here ](https://github.com/Ahmed-ata112/vscode-advanced-new-file/tree/AddNewFileHere-branch)
