### ISSUE TITLE
Please consider a VS-Code compatible changelog

### ISSUE THREAD

**Issue by bbugh** [patbenatar/vscode-advanced-new-file#14]
This extension doesn't have a changelog (at least that VSCode can see). This is really important for deciding what to upgrade in a development environment!

![image](https://cloud.githubusercontent.com/assets/438465/22983451/c1a399d6-f367-11e6-95de-aa06a5532f95.png)

**Comment by patbenatar** [comment]
@bbugh just pushed a small update 0.3.1 that adds a changelog
