### ISSUE TITLE
Nothing happens when I hit enter

### ISSUE THREAD

**Issue by resting** [patbenatar/vscode-advanced-new-file#18]
So I did <kbd>cmd + alt + n</kbd>, then entered a relative path and filename.
Nothing happens when I hit enter after that.
Not such what could be the problem.

VSC: Version 1.10.1 (1.10.1)

**Comment by resting** [comment]
Ah, just noticed I had to select a existing path first.
Works perfectly now :)

**Comment by resting** [comment]
Actually, is there a way to skip the existing path selection?
Have added `"newFile.relativeTo": "file"` but its still prompting me to select a existing path.

**Comment by patbenatar** [comment]
@resting not currently, no. But that's a good feature idea. Will you open a new issue with that feature request? (Also feel free to contribute the feature yourself via PR :) ) Thanks!
