### ISSUE TITLE
I can't use it on Windows

### ISSUE THREAD

**Issue by ylchuai** [patbenatar/vscode-advanced-new-file#20]
I use it on windows7, when I try to use it , show "First, select an existing ...." at the top, and it will close at once. I don't know did I do something wrong?

**Comment by patbenatar** [comment]
@ylchuai what version of VS Code and what version of the plugin? I just checked plugin 0.4.1, VS Code 1.10.2, Windows 10 and it's working—I don't have a Window 7 install on hand to test with.

**Comment by ylchuai** [comment]
@patbenatar I think it is my option have some error, tomorrow I will install it on my workComputer, hope it will be OK. Thank you very much.

**Comment by Kaffiend** [comment]
still issues on windows

**Comment by patbenatar** [comment]
Re-opening #16
