### ISSUE TITLE
Creating a directory does not seem to work

### ISSUE THREAD

**Issue by jonathan-s** [patbenatar/vscode-advanced-new-file#23]
It doesn't seem to work to create a directory even if you use a `/` after the initial directory.

**Comment by jonathan-s** [comment]
You need to provide a file name for the directory to be created as well.

**Comment by patbenatar** [comment]
This functionality should work without a file by postfixing with / in the second dialog. If that's not what you're experiencing, let me know what operating system and VS Code version you're on so we can debug. Thanks!

**Comment by jonathan-s** [comment]
Hi @patbenatar, 
In the second dialogue I had to write `/somefolder/somefile.txt` for it to work properly. If I wrote `/somefolder` it looked like it was creating a file of that. I'm using osx with version Version 1.11.2 (1.11.2) of VS Code.

**Comment by patbenatar** [comment]
@jonathan-s it should work with `somefolder/` (where the `/` is trailing instead of leading)

**Comment by jonathan-s** [comment]
ah, right. Suffix means "after" after all. Perhaps make it even clearer with the example in the docs?

**Comment by patbenatar** [comment]
@jonathan-s good idea! Will you PR an update to the README that makes it more clear? Thanks!

**Comment by jonathan-s** [comment]
Sure!
