### ISSUE TITLE
Does not work [Danish keyboard issue, possible other issues]

### ISSUE THREAD

**Issue by rabol** [patbenatar/vscode-advanced-new-file#3]
Have installed the extension

press comman+alt+n - nothing happens

**Comment by patbenatar** [comment]
@rabol thanks for opening an issue and providing additional information on your marketplace review. Copying that here for convenience:

> In the readme it is stated that one have to hit command+alt+n, it does not work - if I do a shift+command+p and search, then another shortcut is shown command+shift+< - but that combination is not possible on a Mac with a Danish keyboard because as soon as one press shift, the < key becomes >

Happy to help get this issue sorted 😃 

A couple thing to try that will help me debug:

1. Can you try overriding the keyboard shortcut to a shortcut that is accessible on a Danish keyboard? You can do this by going to Code > Preferences > Keyboard Shortcuts in the menu and then adding an entry to the JSON for this extension with a different shortcut, eg:
   ```
   { "key": "alt+cmd+j", "command": "extension.advancedNewFile" }
   ```
1. If you try in a very small project (eg one with < 100 directories and subdirectories), do you get different results?

Thanks!

**Comment by patbenatar** [comment]
Closing this as unresponsive. If Danish keyboard support gets more requests, will reconsider
