### ISSUE TITLE
Does not work with new Insiders multi-root workspaces

### ISSUE THREAD

**Issue by ilkka** [patbenatar/vscode-advanced-new-file#32]
I just upgraded to the Insiders version and started using multi-root workspaces. I noticed an issue where if I have several root directories added to my workspace and use ANF to create a file, it will always be created in the first / topmost root, and its workspace root relative path will contain its absolute _intended_ path. This probably requires an example:

![nayttokuva 2017-08-14 kello 13 30 49](https://user-images.githubusercontent.com/1549/29268290-d327b636-80f4-11e7-8879-28a4e186f0d4.png)
Here I have a workspace with two roots, test1 and test2.

![nayttokuva 2017-08-14 kello 13 31 42](https://user-images.githubusercontent.com/1549/29268316-eeac662c-80f4-11e7-8c84-87d9512d9620.png)
Here I have invoked the ANF action, while having file_in_test2 open in the editor.

![nayttokuva 2017-08-14 kello 13 32 28](https://user-images.githubusercontent.com/1549/29268391-3a16a55a-80f5-11e7-9911-0a6b879afebe.png)
I select the suggested default directory as the base and give the file a name, and press enter.

![nayttokuva 2017-08-14 kello 13 32 35](https://user-images.githubusercontent.com/1549/29268400-4482d8c4-80f5-11e7-9c5a-2bf673a9e86f.png)
The file gets created in test1 instead and with the full absolute path taken as being root-relative. This is not a mere display issue, the directory structure exists on disk.

**Comment by patbenatar** [comment]
@ilkka thanks for testing with multi-root. I'm not surprised that it breaks down, as I understand that update will impact any plugins that use certain VS Code APIs that we're using. How would you expect this plugin to behave when used in a multi-root workspace?

**Comment by ilkka** [comment]
I think current-file-relative paths should work as they do currently, and perhaps the single "workspace root" selection in the first dialog could be replaced with a list of all the roots added to the workspace. As the roots can be anywhere in the filesystem, I think a single root would often not make sense, even if it could be deduced by a common ancestor search.

So, in my example case the first dialog could have the following listing:

- `/Users/ilau/src/testws/test2` -- current file
- `/Users/ilau/src/testws/test1` -- root of `test1`
- `/Users/ilau/src/testws/test2` -- root of `test2`

**Comment by patbenatar** [comment]
@ilkka makes sense to me! I'm pretty busy for the next few weeks; will try to get to this when I have a moment. I'd appreciate your help if you'd be interested in contributing a PR :)

**Comment by patbenatar** [comment]
Here is some guidance from MS: https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs

**Comment by ilkka** [comment]
Hey cool! As it happens I was just trawling for stuff I could submit PRs for for Hacktoberfest, so if you don't already have something cooking, I would like to take a stab at this.

**Comment by patbenatar** [comment]
@ilkka awesome! I haven't started; would love your contribution :)

**Comment by patbenatar** [comment]
@ilkka any luck with this one?

**Comment by ilkka** [comment]
Hey, sorry about that, life kinda intervened :) But I just submitted #42 (which still needs a check for when there are zero workspace roots, I think).

**Comment by patbenatar** [comment]
Multi-root support added in v1.0.0, just released to marketplace
