### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by wangzq** [patbenatar/vscode-advanced-new-file#33]
It seems we are resolving absolute path twice and causing this on Windows: `d:\temp\d:\temp\test.js`, probably not an issue on Mac or Linux.

**Comment by patbenatar** [comment]
@wangzq I'm unable to reproduce this on Windows. Can you provide steps to reproduce, including info about the directory you have opened in your workspace, selection at the first step after launching plugin, input in second step, and result?

Also see my comment on #40

**Comment by chriys** [comment]
@wangzq can't reproduce either. I'm using it both on mac and windows and everything is fine.
