### ISSUE TITLE
Collapse to single step when fuzzy matching finds no results

### ISSUE THREAD

**Issue by strangemonad** [patbenatar/vscode-advanced-new-file#35]
It's annoying to have to first select "/" when a root folder doesn't exist. Forgive me if I'm not correctly understanding the VS Code limitation.

Assuming we currently have a workspace like:
/foo/...
/bar/...

and we type "baz/baz1" into the fuzzy search. Hitting enter should behave as if I had selected "/". i.e. this creates a new file relative to the workspace root. Note that typing "/baz/baz1" should also just work.

**Comment by patbenatar** [comment]
@strangemonad this is a great idea! Would you be interested in contributing a PR?

**Comment by strangemonad** [comment]
I can take a look. I might have some time next week

**Comment by patbenatar** [comment]
@strangemonad I took a look into this and it doesn't appear possible given the VS Code extension limitation noted on the README. Basically: `showQuickPick` only allows users to select from predefined options, so `baz/baz1` results in no match and thus doesn't allow the user to submit. And `showInputBox` doesn't allow for type-ahead matching against predefined options.. so we can't have both interactions in one input, unfortunately.
