### ISSUE TITLE
Performance issues in projects with many directories (eg > 3000)

### ISSUE THREAD

**Issue by patbenatar** [patbenatar/vscode-advanced-new-file#4]
Opening a dedicated issue to track @smukkekim's comment on #1 --

> Ok... It turns out, it actually works, but is VERY slow in large projects...
If I have a few folders in the project, the extension opens near-instantly

>...but my current main project at work, has 3,000+ folders. It takes approx. 30 seconds for the extension dialog to open, after pressing the shortcut.

> I assume it's because it is building the dialog for selecting start-path.
(Why does it not just use the current project root folder as start-path automatically?)

I've experienced this delay on larger projects as well. 

The problem is that we load all the directory paths in the project that so that the user can have a fuzzy autocomplete to find a deep directory that they want to create the new file within. I think the issue lies in one of two things: a) the recursive directory walking and glob matching that builds the array of directories ([here](https://github.com/patbenatar/vscode-advanced-new-file/blob/master/src/extension.ts#L29)); or b) the "quick pick" in VS Code when it's launched with the large array of options ([here](https://github.com/patbenatar/vscode-advanced-new-file/blob/master/src/extension.ts#L14)). I'll see if I can narrow down the problem and then we can discuss solutions.

Related: https://github.com/patbenatar/vscode-advanced-new-file#notes

**Comment by duongphuhiep** [comment]
Hello, 

My project is not big, but the plugin is slow because it tries to load the `node_modules` directory. (Proof: when I delete the `node_modules` folder, the plugin worked great again)

So the plugin should not load this big folder. In other words, it should read the User Settings + Workspace settings and avoid to load the following folders
* `projectManager.vscode.ignoredFolders`
* `projectManager.git.ignoredFolders`
* `projectManager.svn.ignoredFolders`

**Comment by patbenatar** [comment]
@duongphuhiep Great idea, definitely should ignore those workspace ignored folders. The plugin will currently ignore any folders specified in a `.gitignore` file at the workspace root, so for now if you add `node_modules/` to that file, it'll be ignored by the plugin.

**Comment by duongphuhiep** [comment]
Since the beginning, I always have `node_modules/` in my `.gitignore` (of the root project folder). My `git status` had never suggest anything in `node_modules`.

But the plugin seem not take it in account.

**Comment by patbenatar** [comment]
@duongphuhiep can you send me the contents of your gitignore file so I can reproduce and debug?

**Comment by duongphuhiep** [comment]
Here!
it is generated when I created the project

thank you

```
## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# User-specific files
*.suo
*.user
*.userosscache
*.sln.docstates

# User-specific files (MonoDevelop/Xamarin Studio)
*.userprefs

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
[Xx]64/
[Xx]86/
[Bb]uild/
bld/
[Bb]in/
[Oo]bj/

# Visual Studio 2015 cache/options directory
.vs/
# Uncomment if you have tasks that create the project's static files in wwwroot
#wwwroot/

# MSTest test Results
[Tt]est[Rr]esult*/
[Bb]uild[Ll]og.*

# NUNIT
*.VisualState.xml
TestResult.xml

# Build Results of an ATL Project
[Dd]ebugPS/
[Rr]eleasePS/
dlldata.c

# DNX
project.lock.json
artifacts/

*_i.c
*_p.c
*_i.h
*.ilk
*.meta
*.obj
*.pch
*.pdb
*.pgc
*.pgd
*.rsp
*.sbr
*.tlb
*.tli
*.tlh
*.tmp
*.tmp_proj
*.log
*.vspscc
*.vssscc
.builds
*.pidb
*.svclog
*.scc

# Chutzpah Test files
_Chutzpah*

# Visual C++ cache files
ipch/
*.aps
*.ncb
*.opendb
*.opensdf
*.sdf
*.cachefile
*.VC.db

# Visual Studio profiler
*.psess
*.vsp
*.vspx
*.sap

# TFS 2012 Local Workspace
$tf/

# Guidance Automation Toolkit
*.gpState

# ReSharper is a .NET coding add-in
_ReSharper*/
*.[Rr]e[Ss]harper
*.DotSettings.user

# JustCode is a .NET coding add-in
.JustCode

# TeamCity is a build add-in
_TeamCity*

# DotCover is a Code Coverage Tool
*.dotCover

# NCrunch
_NCrunch_*
.*crunch*.local.xml
nCrunchTemp_*

# MightyMoose
*.mm.*
AutoTest.Net/

# Web workbench (sass)
.sass-cache/

# Installshield output folder
[Ee]xpress/

# DocProject is a documentation generator add-in
DocProject/buildhelp/
DocProject/Help/*.HxT
DocProject/Help/*.HxC
DocProject/Help/*.hhc
DocProject/Help/*.hhk
DocProject/Help/*.hhp
DocProject/Help/Html2
DocProject/Help/html

# Click-Once directory
publish/

# Publish Web Output
*.[Pp]ublish.xml
*.azurePubxml

# TODO: Un-comment the next line if you do not want to checkin
# your web deploy settings because they may include unencrypted
# passwords
#*.pubxml
*.publishproj

# NuGet Packages
*.nupkg
# The packages folder can be ignored because of Package Restore
**/packages/*
# except build/, which is used as an MSBuild target.
!**/packages/build/
# Uncomment if necessary however generally it will be regenerated when needed
#!**/packages/repositories.config
# NuGet v3's project.json files produces more ignoreable files
*.nuget.props
*.nuget.targets

# Microsoft Azure Build Output
csx/
*.build.csdef

# Microsoft Azure Emulator
ecf/
rcf/

# Windows Store app package directory
AppPackages/
BundleArtifacts/

# Visual Studio cache files
# files ending in .cache can be ignored
*.[Cc]ache
# but keep track of directories ending in .cache
!*.[Cc]ache/

# Others
ClientBin/
[Ss]tyle[Cc]op.*
~$*
*~
*.dbmdl
*.dbproj.schemaview
*.pfx
*.publishsettings
node_modules/
orleans.codegen.cs

# RIA/Silverlight projects
Generated_Code/

# Backup & report files from converting an old project file
# to a newer Visual Studio version. Backup files are not needed,
# because we have git ;-)
_UpgradeReport_Files/
Backup*/
UpgradeLog*.XML
UpgradeLog*.htm

# SQL Server files
*.mdf
*.ldf

# Business Intelligence projects
*.rdl.data
*.bim.layout
*.bim_*.settings

# Microsoft Fakes
FakesAssemblies/

# GhostDoc plugin setting file
*.GhostDoc.xml

# Node.js Tools for Visual Studio
.ntvs_analysis.dat

# Visual Studio 6 build log
*.plg

# Visual Studio 6 workspace options file
*.opt

# Visual Studio LightSwitch build output
**/*.HTMLClient/GeneratedArtifacts
**/*.DesktopClient/GeneratedArtifacts
**/*.DesktopClient/ModelManifest.xml
**/*.Server/GeneratedArtifacts
**/*.Server/ModelManifest.xml
_Pvt_Extensions

# LightSwitch generated files
GeneratedArtifacts/
ModelManifest.xml

# Paket dependency manager
.paket/paket.exe

# FAKE - F# Make
.fake/

.idea/**/contentModel.xml
.idea/**/modules.xml
.idea/**/workspace.xml
.idea/**/*.iml
```

**Comment by patbenatar** [comment]
@duongphuhiep Thanks! I created a dedicated issue for this https://github.com/patbenatar/vscode-advanced-new-file/issues/6

**Comment by patbenatar** [comment]
Some fixes to gitignore and VSCode ignore settings drastically improve performance in projects where the bulk of the directories are in fact ignored (ie `node_modules/` dirs)

**Comment by smukkekim** [comment]
Wow! That certainly improved things. On my massive work project with over 3000 folders, the reaction time from shortcut-activation to dialog display went from 30+ seconds to ~3 seconds!

**Comment by patbenatar** [comment]
@smukkekim glad to hear it!

**Comment by patbenatar** [comment]
I think this is now just about as good as we can get it without making a fundamental tech switch (eg replacing the glob search with a C implementation). Given that I haven't heard further complaints in a couple months, closing it out.

**Comment by Kaffiend** [comment]
Most likely a node_modules dirextory causing an issue? Perhaps inherit
vscodes directory search ignore settings?

**Comment by patbenatar** [comment]
@Kaffiend precisely! Honoring of gitignores and vscode workspace ignore settings are some of the improvements rolled out over the past couple months that have addressed this issue

**Comment by Kaffiend** [comment]
Awesome!
