### ISSUE TITLE
pressing return/enter after specifing the path does nothing?

### ISSUE THREAD

**Issue by a-eid** [patbenatar/vscode-advanced-new-file#44]
I'm using the latest version of code `1.18.1` 
and have just installed the extension, 

after I specify the path pressing return/enter has no effect what so ever.

**Comment by patbenatar** [comment]
@a-eid what OS are you on?

**Comment by a-eid** [comment]
@patbenatar 

macOS High Sierra.

its probably worth mentioning that when I select a file from the sidebar with my arrow keys and hit enter/return it puts me in a rename mode which I have been told is not the way it should behave.

could that be the issue?

**Comment by patbenatar** [comment]
@a-eid I'm not able to reproduce on my mac running High Sierra. Is the issue happening for you on all of your workspaces or only a specific one/few? Would you be able to clone this repo and try running it locally in development to see if you get errors in the console?

**Comment by a-eid** [comment]
@patbenatar I have only tried the extension on this workspace. I don't currently get any errors. 
I will close the issue, clone the repo and look more into it. 

could you confirm the issue with the sidebar. 
selecting a file/folder with your arrow keys and hitting enter does it but your cursor in the editor area, or does it try renaming it.

**Comment by patbenatar** [comment]
@a-eid thanks for helping debug! I'm actually going to reopen this issue since someone else +1'd it so it's not just isolated to your environment.

My sidebar is behaving similarly to yours: arrow keys and hitting enter tries to rename.

**Comment by patbenatar** [comment]
@misenhower thanks for following up.

Closing this out pending further info from @a-eid
