### ISSUE TITLE
Setting to prioritize "current file" over "last selection"

### ISSUE THREAD

**Issue by gabrielecirulli** [patbenatar/vscode-advanced-new-file#45]
Thanks a lot for this extension, it was one of my main holdouts while switching from Sublime Text and it has made the transition much more painless.

While using the Sublime Text version, I found myself always using the "current file" option (this is because the first item in the list was always the current path). In this extension, it is shown as the second path in the list below "last selection" if present. 

For my use-case, having a way to show "current file" as the first item would always save me a keystroke and allow me to just blindly press enter on the prompt as it always shows what I expect as the first option.

I completely understand that everyone's workflow is different so I'd propose to offer this as a setting. If justified, the setting could even allow you to just order the three options: `workspace root`, `current file` and `last selection` as you choose.

Could this be an interesting addition to the extension?

**Comment by patbenatar** [comment]
@gabrielecirulli thanks for the kind words! Glad to hear it's helping out your workflow. I agree this is a good idea for an improvement. I'll look into it when I have a moment, or you're welcome to open a PR :) (if you're interested, I'd suggest waiting for #46 to merge as it introduces some refactors that will make this feature easier to add)
