### ISSUE TITLE
The extension contains the whole Visual Studio Code App

### ISSUE THREAD

**Issue by ngocphamm** [patbenatar/vscode-advanced-new-file#47]
At first, I noticed that the it takes a long time to install the extension. Then this is what I found.

```
~/.v/extensions »  du -sh dkundel.vscode-new-file-4.0.0
290M    dkundel.vscode-new-file-4.0.0
~/.v/extensions »  cd dkundel.vscode-new-file-4.0.0
~/.v/e/dkundel.vscode-new-file-4.0.0 »  du -sh .vscode-test
286M    .vscode-test
~/.v/e/dkundel.vscode-new-file-4.0.0 »  ll .vscode-test
total 0
drwxr-xr-x   3 ngoc  staff   96 Dec 11 22:56 .
drwxr-xr-x  15 ngoc  staff  480 Dec 11 22:56 ..
drwxr-xr-x   3 ngoc  staff   96 Dec 11 22:56 Visual Studio Code.app
~/.v/e/dkundel.vscode-new-file-4.0.0 »
```

So basically it contains the whole Visuao Studio Code app itself!

Does anyone know the reason why?

**Comment by patbenatar** [comment]
That isn’t this plugin. I think you’re looking for https://github.com/dkundel/vscode-new-file

**Comment by ngocphamm** [comment]
I am terribly sorry. I opened too many tabs and ended up posting in the wrong repo :-(

**Comment by patbenatar** [comment]
Ha! No worries :)

You can give this plugin a shot as an alternative if you’re having issues with the other

**Comment by ngocphamm** [comment]
I actually used this one without no problem until I got into multi-root workspace and this one has not been supported (yet). I figured soon because of the pull requests, but I just gave the other one a shot.

**Comment by patbenatar** [comment]
@ngocphamm multi-root support has been added in 1.0.0, just released to marketplace

**Comment by ngocphamm** [comment]
@patbenatar Awesome! I'm coming back to this extension!

**Comment by patbenatar** [comment]
:+1: let me know how it works for you

**Comment by ngocphamm** [comment]
It's working fine but I wish if it can remember the last selected root to start with.

**Comment by patbenatar** [comment]
@ngocphamm good idea, I just created a separate issue for it: #48
