### ISSUE TITLE
In multi-root workspaces, order directory options by last used root

### ISSUE THREAD

**Issue by patbenatar** [patbenatar/vscode-advanced-new-file#48]

**Comment by patbenatar** [comment]
@ngocphamm just released this in 1.1.0

**Comment by ngocphamm** [comment]
Awesome! I was thinking it won't "ask" for which root to start with that I will just have to type in file name to create but it actually "remembers" the last option to pre-selects it. One more Enter away is not bad! Thank you @patbenatar!!!
