### ISSUE TITLE
Ignore directories specified in workspace config

### ISSUE THREAD

**Issue by patbenatar** [patbenatar/vscode-advanced-new-file#5]
Cross-posted from https://github.com/patbenatar/vscode-advanced-new-file/issues/4#issuecomment-279059490

* Native setting is `files.exclude`

There's also a `projectManager` extension that adds these settings which have been requested:

* `projectManager.vscode.ignoredFolders`
* `projectManager.git.ignoredFolders`
* `projectManager.svn.ignoredFolders`

**Comment by patbenatar** [comment]
@duongphuhiep latest release 0.2.0 adds support for `files.exclude` which is VSCode's native user and workspace setting for managing ignored files. I opted for adding support for the native setting rather than the `projectManager` plugin settings since not all users are using that plugin.

**Comment by Kaffiend** [comment]
Would be nice to just specify a separate config property in the workspace config or user config like vscodevim does or inherit from .gitignore as that is a closer match to traversal directories to exclude, this feels like a workaround as there are reasons to see your node_modules directory and dist directories in vscode but will never need the extension to traverse them in the fuzzy finder.

**Comment by patbenatar** [comment]
@Kaffiend it currently will honor both `.gitignore`, are you observing behavior that suggests it's not honoring your gitignore?

**Comment by Kaffiend** [comment]
Possibly. Im still investigating it. I know the problem lies with an electron dist directory and native node modules separate from the project node modules. And the only solution that worked was the vscode exclude. But there may be a bad gitignore entry that i overlooked. I will double check this evening.

**Comment by patbenatar** [comment]
Thanks @Kaffiend — keep me posted

**Comment by Kaffiend** [comment]
@patbenatar Looks like its not honoring the following directories from the `.gitignore`
```
# Dist #
/dist
node_modules_electron/
dev/
packages/
```
it possibly may be hitting the root `node_modules` directory as well. Once i add those to the vscode workspace exlude array, the performance is great.
