### ISSUE TITLE
disable created directory and file notification

### ISSUE THREAD

**Issue by Kaffiend** [patbenatar/vscode-advanced-new-file#51]
My main driving factor is the mouse-free friendly-ness this extension provides. Allow an option to disable the created message that has to be clicked to dismiss. This is rather annoying when creating multiple directories. These stackup and block the fuzzy finder on the next usage.

![image](https://user-images.githubusercontent.com/7826229/35636823-620066f8-0680-11e8-8831-548ad2625cdc.png)

**Comment by Kaffiend** [comment]
Disregard, i found the setting. Thanks

**Comment by patbenatar** [comment]
😃

**Comment by Kaffiend** [comment]
Think i actually complained about this a while back just didn't see the issue 😄 and just out of curiosity i looked in user settings 😁
