### ISSUE TITLE
Feature: Ctrl-n/Ctrl-p to navigate list

### ISSUE THREAD

**Issue by karptonite** [patbenatar/vscode-advanced-new-file#52]
While it is possible to navigate the directory list with the arrow keys, it would be nice to also be able to use ctrl-n(ext) and ctrl-p(revious), as I believe we can in other such menus in vs-code. (I say "I believe" because it works for me, but I'm not 100% sure it also works by default).

**Comment by patbenatar** [comment]
@karptonite unfortunately we don't have control over the interaction in that picker box, it's a built-in VS Code component: `vscode.window.showQuickPick` https://code.visualstudio.com/docs/extensionAPI/vscode-api

It's unfortunate that some native menus in VS Code seem to support that behavior, while the menu made available to extension developers doesn't :(

**Comment by patbenatar** [comment]
@karptonite you might consider opening a feature request with VS Code to see if they'll implement this in the extension quickpick
