### ISSUE TITLE
Slow, unless I exclude "public" folder

### ISSUE THREAD

**Issue by ldiebold** [patbenatar/vscode-advanced-new-file#53]
I have a Laravel Project and wasn't able to use this plugin because it took too long to load (never waited long enough to see if it loaded at all)

I fixed this by excluding the "public" folder

Here's the entire contents of my public folder:

![image](https://user-images.githubusercontent.com/1305724/36292818-a5941ec8-1328-11e8-8f53-7ce67dff8d04.png)

Why would this fix the issue? There's practically nothing in there!

Running Windows 7

**Comment by patbenatar** [comment]
@ldiebold very interesting, thanks for the report. It looks like that screenshot is taken from within VS Code sidebar, can you verify that it's the same contents outside of VS Code (e.g. using `tree` at the command line)? I want to make sure VS Code isn't filtering out files or directories from its display.

**Comment by bfranklyn** [comment]
is it possible to implement some sort of caching? I noticed each time hit the advanced new file command it loads the project again.

**Comment by ldiebold** [comment]
@patbenatar unfortunately, I cleared out my public folder before performing the "tree" command. Now everything is working!

Sorry I replied too late and wasn't able to give more insight.

**Comment by patbenatar** [comment]
@ldiebold hmm sounds like you may have had some large hidden directory tree inside of public, given that it works fine after emptying public. :-/

@bfranklyn agreed, speeding up the directory picker launch time is an important thing to focus on. I've considered caching the directory options in the past but didn't come up with a good solution for invalidation and updating the cache to ensure you can always find the directories you want, regardless of when that directory was created or the last time you ran the command and thus generated a cache. 

My thought right now is to always regenerate the cache in the background every time you run the command, while presenting options to the user from cache right away. Problem is VS Code doesn't let us update the options in that picker after we've presented it to the user, so if the user has just added a new directory via some other method than this plugin they wouldn't be able to select it the following time they run the command -- we'd always be showing the state of the directory tree from the last time you ran the command.

Thoughts?
