### ISSUE TITLE
feature request: create new file in current split

### ISSUE THREAD

**Issue by xiechao06** [patbenatar/vscode-advanced-new-file#56]
Eg. If I split the editor, and focus on the right window, and create a new file, I wish the newly created file is displayed in the right window.

**Comment by patbenatar** [comment]
Good idea @xiechao06 

I think this can be done easily via `showTextDocument(document: TextDocument, column?: ViewColumn, preserveFocus?: boolean): Thenable<TextEditor>` using `ViewColumn.active`: https://code.visualstudio.com/docs/extensionAPI/vscode-api#ViewColumn

**Comment by patbenatar** [comment]
@xiechao06 just published a new version with this functionality
