### ISSUE TITLE
[feature request] consider adding rename and delete current file commands

### ISSUE THREAD

**Issue by acheronfail** [patbenatar/vscode-advanced-new-file#60]
Sublime Text's [AdvancedNewFile](https://github.com/skuroda/Sublime-AdvancedNewFile) package provides commands for `Delete Current File` and `Rename Current File` (among others) which are really nice to use from the command palette.

For a list of their supported commands, [see here](https://github.com/skuroda/Sublime-AdvancedNewFile/wiki/Commands).

Would you consider adding any of these commands? Or at the least `Delete Current File` and `Rename Current File`?

**Comment by patbenatar** [comment]
@acheronfail I'd recommend https://github.com/sleistner/vscode-fileutils — that plugin does what you're describing very well

**Comment by acheronfail** [comment]
Wow, I'd just come across that and was about to close this issue and mention that!

Thanks all the same for providing the link. :)

**Comment by patbenatar** [comment]
Ha! What a coincidence. Cheers
