### ISSUE TITLE
Dialog input not responding

### ISSUE THREAD

**Issue by BrewCurious** [patbenatar/vscode-advanced-new-file#64]
I'm relatively new to VS Code and just installed the advanced-new-file extension on my work Mac today. It appeared to install fine, reloaded the editor to enable, but when I pull up the dialog for creating a new file (using either the hotkey combination or the command palette), it shows the "loading" bar underneath for about 5 seconds, presents no file/directory suggestions and then disappears. Typing anything into the dialog box doesn't appear to change anything.

OS: OSX High Sierra v10.13.6

**Comment by pgdaniel** [comment]
Closing old issues, re-open if you feel this is still an issue.
