### ISSUE TITLE
Create multiple files in one go

### ISSUE THREAD

**Issue by timlogemann** [patbenatar/vscode-advanced-new-file#69]
It would be great if it was possible to create multiple files in one command, similar to how the other "Advanced New File" plugin allows you to do so:
https://marketplace.visualstudio.com/items?itemName=dkundel.vscode-new-file

it allows you to write something like `{file1.js, file2.js}` and it will create 2 files for you in the specified directory. It would also be nice to allow it as a sub part, so you could write `component.{jsx,css}` and end up with `component.jsx` and `component.css`

**Comment by chuckhendo** [comment]
I added brace expansion to the other plugin! I'll take a look to see what it would take to add to this one (assuming this extension is still maintained, @patbenatar are you accepting PRs for this repo?)

**Comment by patbenatar** [comment]
@chuckhendo absolutely open to PRs :) -- I haven't personally had time to work on this project in a while, but I'd love collaborators.
