### ISSUE TITLE
Extension breaks after change to limit glob search to directories

### ISSUE THREAD

**Issue by matthewmcgarvey** [patbenatar/vscode-advanced-new-file#81]
I'm assuming it is because of the change found here: https://github.com/patbenatar/vscode-advanced-new-file/blob/774fc3377d8774546cb578d1ee62da5a6ee2d359/src/extension.ts#L81

This is not to say that they change is bad but I have had to revert back to the previous version of the extension.

I have a project with a public directory and a `mix-manifest.json` file inside it. The extension fails saying that `path/to/mix-manifest.json/**` is not a directory. This file is generated by laravel mix.

**Comment by rpbaltazar** [comment]
I am facing the same issue in my rails project. Extension does not work unless I remove my `config/puma.rb` file, with exactly the same message:
`ENOTDIR: not a directory, stat '<application_path>/config/puma.rb/**'`

**Comment by rpbaltazar** [comment]
Reverting back to the 1.2.0 solves the issue

**Comment by patbenatar** [comment]
Temporarily reverted globby change in 1.2.2 which should fix this issue for the meantime. Let me know.

**Comment by JoeNg93** [comment]
@rpbaltazar @matthewmcgarvey Might I know which OS you guys are using? So that I can try to reproduce the issue.

**Comment by matthewmcgarvey** [comment]
I'm using a Mac

**Comment by rpbaltazar** [comment]
same here

**Comment by matthewmcgarvey** [comment]
Year and a half and 2 jobs later, ran into this issue again 🤦

**Comment by matthewmcgarvey** [comment]
Change was reverted here: https://github.com/patbenatar/vscode-advanced-new-file/commit/0142d5d57303ae952bd0c9bc5ff9582a436d1c67

Thanks!
