### ISSUE TITLE
OpenVSX

### ISSUE THREAD

**Issue by dixiedream** [patbenatar/vscode-advanced-new-file#87]
Please upload your extension to openVSX as my Arch installation stop finding it after the marketplace switch.

Thanks

**Comment by rafiazman** [comment]
I use VSCodium myself and have found this extension to be super nifty on my VSCode install on a separate machine.

Would be great to see this published on Open VSX as well 😄 

They have published documentation for the publishing process [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by patbenatar** [comment]
@dixiedream @rafiazman finally got around to this -- I think I've done it, can you please verify?

```
🚀  Published giantcola.advanced-new-file v1.2.2
```

**Comment by rafiazman** [comment]
Thank you for taking the steps to publish it! 😁

I see it published now as "giantcola.advanced-new-file". I have requested for the other listing to be removed (published by Open VSX on my request).

See: https://github.com/open-vsx/publish-extensions/pull/301
