### ISSUE TITLE
Cannot use the extension - error upon initially executing command, where you type in the path

### ISSUE THREAD

**Issue by AlanHeckinJohnston** [patbenatar/vscode-advanced-new-file#95]
Path input appears in console for about a quarter of a second, then I get
`Running the contributed command: 'extension.advancedNewFile' failed.`
and it closes.

Did uninstall, restart, etc. I'm on windows and the project is within WSL. Note that it worked perfectly for a long time, but stopped working suddenly.

Note: downgrading to 1.2.1 resolves the issue.

**Comment by pgdaniel** [comment]
Hi @AlanHeckinJohnston can you give me some more details around your environment? I'm not able to reproduce.

**Comment by pgdaniel** [comment]
@AlanHeckinJohnston it might be that you have broken simlinks, try using this command from the command line in the root of your project `find . -xtype l`

**Comment by AlanHeckinJohnston** [comment]
@pgdaniel yes, there was one broken simlink and after removing it the extension works fine.
