### ISSUE TITLE
Cannot create new file when one file is opened

### ISSUE THREAD

**Issue by Marskritiqual** [patbenatar/vscode-advanced-new-file#96]
When focusing on a file, pressing the keyboard shortcut for open new file keep open this message: "Running the contributed command: 'extension.advancedNewFile' failed."

**Comment by pgdaniel** [comment]
@Marskritiqual are you still having this problem? I was unable to reproduce. Can you give more details about your environment?

**Comment by pgdaniel** [comment]
I'm going to assume this is probably a bad symlink. If it is not feel free to reopen
